<a href="https://colab.research.google.com/github/JorgeVitor30/Curso-Data-Science/blob/main/Aula3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.naive_bayes import GaussianNB

In [ ]:
base_risco_credito = pd.read_csv("/content/risco_credito.csv")

In [ ]:
base_risco_credito

historia divida garantias          renda     risco
0           ruim   alta   nenhuma           0_15      alto
1   desconhecida   alta   nenhuma          15_35      alto
2   desconhecida  baixa   nenhuma          15_35  moderado
3   desconhecida  baixa   nenhuma       acima_35      alto
4   desconhecida  baixa   nenhuma       acima_35     baixo
5   desconhecida  baixa  adequada       acima_35     baixo
6           ruim  baixa   nenhuma           0_15      alto
7           ruim  baixa  adequada       acima_35  moderado
8            boa  baixa   nenhuma       acima_35     baixo
9            boa   alta  adequada  acima_35baixo       NaN
10           boa   alta   nenhuma           0_15      alto
11           boa   alta   nenhuma          15_35  moderado
12           boa   alta   nenhuma       acima_35     baixo
13          ruim   alta   nenhuma          15_35      alto

In [ ]:
base_risco_credito["risco"].fillna('baixo', inplace = True)

In [ ]:
base_risco_credito

historia divida garantias          renda     risco
0           ruim   alta   nenhuma           0_15      alto
1   desconhecida   alta   nenhuma          15_35      alto
2   desconhecida  baixa   nenhuma          15_35  moderado
3   desconhecida  baixa   nenhuma       acima_35      alto
4   desconhecida  baixa   nenhuma       acima_35     baixo
5   desconhecida  baixa  adequada       acima_35     baixo
6           ruim  baixa   nenhuma           0_15      alto
7           ruim  baixa  adequada       acima_35  moderado
8            boa  baixa   nenhuma       acima_35     baixo
9            boa   alta  adequada  acima_35baixo     baixo
10           boa   alta   nenhuma           0_15      alto
11           boa   alta   nenhuma          15_35  moderado
12           boa   alta   nenhuma       acima_35     baixo
13          ruim   alta   nenhuma          15_35      alto

In [ ]:
X_risco_credito = base_risco_credito.iloc[:, 0:4].values

In [ ]:
X_risco_credito

array([['ruim', 'alta', 'nenhuma', '0_15'],
       ['desconhecida', 'alta', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'adequada', 'acima_35'],
       ['ruim', 'baixa', 'nenhuma', '0_15'],
       ['ruim', 'baixa', 'adequada', 'acima_35'],
       ['boa', 'baixa', 'nenhuma', 'acima_35'],
       ['boa', 'alta', 'adequada', 'acima_35baixo'],
       ['boa', 'alta', 'nenhuma', '0_15'],
       ['boa', 'alta', 'nenhuma', '15_35'],
       ['boa', 'alta', 'nenhuma', 'acima_35'],
       ['ruim', 'alta', 'nenhuma', '15_35']], dtype=object)

In [ ]:
y_risco_credit = base_risco_credito.iloc[:, 4].values

In [ ]:
y_risco_credit

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder_historia = LabelEncoder()
label_encoder_divida = LabelEncoder()
label_encoder_garantia = LabelEncoder()
label_encoder_renda = LabelEncoder()

In [ ]:
X_risco_credito[:, 0] = label_encoder_historia.fit_transform(X_risco_credito[:, 0])
X_risco_credito[:, 1] = label_encoder_divida.fit_transform(X_risco_credito[:, 1])
X_risco_credito[:, 2] = label_encoder_garantia.fit_transform(X_risco_credito[:, 2])
X_risco_credito[:, 3] = label_encoder_renda.fit_transform(X_risco_credito[:, 3])





In [ ]:
X_risco_credito


array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 3],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [ ]:
X_risco_credito[9] = [0,0,0,2]  # ERRO NO DATASET

In [ ]:
import pickle
with open('risco_credito.pkl', "wb") as f:
  pickle.dump([X_risco_credito, y_risco_credit], f)


In [ ]:
naive_risco_credito = GaussianNB()
naive_risco_credito.fit(X_risco_credito, y_risco_credit)    #PRIMEIRO PARÂMETRO OS ATRIBUTOS PREVISORES E O SEGUNDO É A CLASSE (RESPOSTA ESPERADA)


GaussianNB()

In [ ]:
# # história boa (0), dívida alta (0), garantias nenhuma (1), renda > 35 (2)    RISCO BAIXO
# história ruim (2), dívida alta (0), garantias adequada (0), renda < 15 (0)    RISCO MODERADO
previsao = naive_risco_credito.predict([[0,0,1,2], [2,0,0,0]])  # AS 2 SITUAÇÕES CADASTRADAS

In [ ]:
previsao    # PROVA QUE O ALGORITMO FOI TREINADO CERTO

array(['baixo', 'moderado'], dtype='<U8')

In [ ]:
naive_risco_credito.classes_

array(['alto', 'baixo', 'moderado'], dtype='<U8')

In [ ]:
naive_risco_credito.class_count_    # CONTAGEM DOS REGISTROS DAS CLASSES

array([6., 5., 3.])

In [ ]:
naive_risco_credito.class_prior_          # REPRESENTAÇÃO DAS PORCENTAGENS DAS QUANTIDADES DAS CLASSES NA DB

array([0.42857143, 0.35714286, 0.21428571])