<a href="https://colab.research.google.com/github/JorgeVitor30/Curso-Data-Science/blob/main/Estudo_de_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ESTUDO DE NUMPY

In [41]:
import numpy as np

In [42]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [43]:
kanto = np.array([73, 67, 43])

In [44]:
kanto

array([73, 67, 43])

In [45]:
weights = np.array([w1,w2,w3])

In [46]:
weights

array([0.3, 0.2, 0.5])

In [47]:
weights[0]

0.3

# Operations on Numpy arrays

In [48]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [49]:
np.dot(kanto,weights)

56.8

In [50]:
a = [1,2]
b = [2,3]
np.dot(a,b)

8

In [51]:
(kanto * weights).sum()     # MSM FUNCIONAMENTO DO DOT (MULTIPLICAR AS LISTAS E SOMAR OS RESULTADOS)

56.8

# Multi-dimensional Numpy arrays

In [52]:
climate_data = np.array([[10,20,30],
                [40,50,60],
                [70,80,90],
                [100,110,120]])

In [53]:
climate_data      #2D

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [54]:
climate_data.shape

(4, 3)

In [55]:
climate_data_3d = np.array([ 
        [[10,20,30],
         [40,50,60]],

         [[70,80,90],
         [100,110,120]]])

In [56]:
climate_data_3d.shape

(2, 2, 3)

#Working with CSV

In [57]:
import urllib.request

urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f599c3668f0>)

In [58]:
climate_data = np.genfromtxt('climate.txt', delimiter= ',' , skip_header=1)

In [59]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [60]:
climate_data.shape

(10000, 3)

In [61]:
weights = np.array([0.3, 0.2, 0.5])
teste = np.array([0.4, 0.3, 0.6])

In [62]:
concatenado = np.concatenate((weights, teste))

In [63]:
concatenado

array([0.3, 0.2, 0.5, 0.4, 0.3, 0.6])

In [64]:
concatenado.shape

(6,)

In [65]:
teste.reshape(3,1)    # MUDA A QTD DE COLUNAS E LINHAS Q EU QUERO (DE ACORDO COM A QTD ORIGINAL DA LISTA) --> TORNOU-SE EM UMA LISTA DE 3 LINHAS E 1 COLUNA

array([[0.4],
       [0.3],
       [0.6]])

In [66]:
np.savetxt('climate_data', 
            climate_data,
            fmt='%.2f',
            header='temperature,rainfall,humidity,yeild_apples',
            comments=' ')

# Arithmetic operations and broadcasting

In [67]:
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 1, 2, 3]])

In [68]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [69]:
arr2 + arr3

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 12, 14, 16]])

In [70]:
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [71]:
arr2 + 3      # SOMAR 3 A TODOS OS ELEMENTOS DA LISTA NP

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [72]:
arr3 / 3    # DIVIDIR POR 3 A TODOS OS ELEMENTOS DA LISTA NP

array([[3.66666667, 4.        , 4.33333333, 4.66666667],
       [5.        , 5.33333333, 5.66666667, 6.        ],
       [6.33333333, 3.66666667, 4.        , 4.33333333]])

In [73]:
arr2.shape

(3, 4)

In [74]:
arr4 = np.array([4,5,6,7])

In [75]:
arr4.shape

(4,)

In [76]:
arr2 + arr4     # está somando [4,5,6,7] em todas as linhas       ex: [1,2,3,4] + [4,5,6,7]   //  [5, 6, 7, 8] + [4, 5, 6, 7]

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [77]:
arr5 = np.array([7, 8])

In [78]:
arr5.shape

(2,)

In [79]:
arr5_replicated = np.array([[7, 8],
                           [7, 8],
                           [7, 8]])

In [80]:
arr5 = np.array([[1, 2, 3], [3, 4, 5]])
arr6 = np.array([[2, 2, 3], [1, 2, 5]])

In [81]:
arr5 == arr6        # FAZ UMA COMPARAÇÃO DE ELEMENTO POR ELEMENTO

array([[False,  True,  True],
       [False, False,  True]])

In [82]:
arr5 != arr6        # FAZ UMA COMPARAÇÃO DE ELEMENTO POR ELEMENTO

array([[ True, False, False],
       [ True,  True, False]])

In [83]:
arr5 >= arr6       # FAZ UMA COMPARAÇÃO DE ELEMENTO POR ELEMENTO 

array([[False,  True,  True],
       [ True,  True,  True]])

In [84]:
arr5 <= arr6      # FAZ UMA COMPARAÇÃO DE ELEMENTO POR ELEMENTO

array([[ True,  True,  True],
       [False, False,  True]])

In [85]:
(arr5 == arr6).sum()      # SOMATÓRIA DE QNTS ELEMENTOS SÃO IGUAIS

3

In [86]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [87]:
climate_data[1]

array([39., 65., 70.])

In [88]:
climate_data_3d = np.array([ 
        [[10,20,30],
         [40,50,60]],

         [[70,80,90],
         [100,110,120]]])

In [89]:
climate_data_3d[1,1,1]

110

In [90]:
climate_data_3d[1][1][1]

110

In [91]:
climate_data_3d[1:, :2, 1:]     # MANIPULAÇÕES ESPECÍFICAS

array([[[ 80,  90],
        [110, 120]]])

In [92]:
climate_data_3d[1:, :2, 1:].shape

(1, 2, 2)

# CRIAR COM TUDO ZERO



In [93]:
np.zeros([3, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# CRIAR COM TODOS 1

In [94]:
np.ones([2,2,1])

array([[[1.],
        [1.]],

       [[1.],
        [1.]]])

# CRIAR RANDOM VETOR

In [95]:
np.random.rand(5)

array([0.2063755 , 0.29282551, 0.44753361, 0.6707638 , 0.7840969 ])

In [96]:
np.random.randn(2,3)    # GAUSSIAN

array([[-0.43665626, -0.25858779, -0.8231653 ],
       [-0.39586261, -1.64008815,  2.37064404]])

In [97]:
np.full([2,3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [98]:
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [99]:
np.arange(10, 90, 3).shape

(27,)

In [100]:
np.arange(10, 90, 3).reshape(3, 3, 3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [101]:
np.linspace(3, 27, 4)     # SETA O ESPAÇAMENTO ENTRE O RANGE DE ACORDO COM O TANTO DE ELEMENTOS Q EU QUERO QUE TENHA NO RANGE (3, 27)

array([ 3., 11., 19., 27.])

In [104]:
A = np.array([ [1,2,3],
              [4,5,6],
              [7,6,9]])

In [109]:
A[0] = np.array([[3,3,3]])

In [108]:
A

array([[3, 3, 3],
       [4, 5, 6],
       [7, 6, 9]])

In [110]:
A[2] = 0 

In [111]:
A

array([[3, 3, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [112]:
A.sum()

24

In [113]:
A.mean()

2.6666666666666665

In [116]:
A[0].mean()  

3.0

In [121]:
A.sum(axis=0)     # SOMAS DAS COLUNAS (0 NO EXEMPLO)

array([7, 8, 9])

In [122]:
A.mean(axis=0) # MÉDIA DAS COLUNAS (0 NO EXEMPLO)

array([2.33333333, 2.66666667, 3.        ])

In [120]:
A.std()     # Desvio Padrão

2.1081851067789197

In [124]:
A.var()   # Usada para calcular a variância dos elementos da matriz

4.444444444444445

In [129]:
B = np.random.randint(100, size=(3,3))

In [130]:
B

array([[84, 94, 61],
       [39, 47, 14],
       [12, 31,  8]])

In [139]:
B.mean()

43.333333333333336

In [134]:
B > 40      # Return Booleans values

array([[ True,  True,  True],
       [False,  True, False],
       [False, False, False]])

In [135]:
B[B>40]   # Get the values

array([84, 94, 61, 47])

In [142]:
B[B>B.mean()]

array([84, 94, 61, 47])

In [143]:
C = np.arange(20)   # Example template np array 

In [144]:
C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [146]:
a = np.array([1,2,3])
b = np.array([10,20,30])
a.dot(b)    

140

In [147]:
a @ b

140

In [150]:
d = np.array([[1],
             [2]])

In [151]:
d.T       # Transposta

array([[1, 2]])

In [152]:
A

array([[3, 3, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [158]:
D = np.array([[1,2],
             [1,3],
              [3,5]])

In [159]:
D

array([[1, 2],
       [1, 3],
       [3, 5]])

In [160]:
A.dot(D)

array([[15, 30],
       [27, 53],
       [ 0,  0]])

In [163]:
A @ D

array([[15, 30],
       [27, 53],
       [ 0,  0]])

In [172]:
D.T

array([[1, 1, 3],
       [2, 3, 5]])

In [171]:
D.T @ A

array([[ 7,  8,  9],
       [18, 21, 24]])

In [182]:
test = np.empty(())

In [183]:
test

array(8.70018275e-313)

In [185]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [186]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])