<a href="https://colab.research.google.com/github/JorgeVitor30/Curso-Data-Science/blob/main/Estudo_de_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ESTUDO DE NUMPY

In [3]:
import numpy as np

In [4]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [5]:
kanto = np.array([73, 67, 43])

In [6]:
kanto

array([73, 67, 43])

In [7]:
weights = np.array([w1,w2,w3])

In [8]:
weights

array([0.3, 0.2, 0.5])

In [9]:
weights[0]

0.3

# Operations on Numpy arrays

In [10]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [11]:
np.dot(kanto,weights)

56.8

In [12]:
a = [1,2]
b = [2,3]
np.dot(a,b)

8

In [13]:
(kanto * weights).sum()     # MSM FUNCIONAMENTO DO DOT (MULTIPLICAR AS LISTAS E SOMAR OS RESULTADOS)

56.8

# Multi-dimensional Numpy arrays

In [14]:
climate_data = np.array([[10,20,30],
                [40,50,60],
                [70,80,90],
                [100,110,120]])

In [15]:
climate_data      #2D

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [16]:
climate_data.shape

(4, 3)

In [17]:
climate_data_3d = np.array([ 
        [[10,20,30],
         [40,50,60]],

         [[70,80,90],
         [100,110,120]]])

In [18]:
climate_data_3d.shape

(2, 2, 3)

#Working with CSV

In [19]:
import urllib.request

urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7fb2a7ab5690>)

In [20]:
climate_data = np.genfromtxt('climate.txt', delimiter= ',' , skip_header=1)

In [21]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [22]:
climate_data.shape

(10000, 3)

In [23]:
weights = np.array([0.3, 0.2, 0.5])
teste = np.array([0.4, 0.3, 0.6])

In [24]:
concatenado = np.concatenate((weights, teste))

In [25]:
concatenado

array([0.3, 0.2, 0.5, 0.4, 0.3, 0.6])

In [26]:
concatenado.shape

(6,)

In [27]:
teste.reshape(3,1)    # MUDA A QTD DE COLUNAS E LINHAS Q EU QUERO (DE ACORDO COM A QTD ORIGINAL DA LISTA) --> TORNOU-SE EM UMA LISTA DE 3 LINHAS E 1 COLUNA

array([[0.4],
       [0.3],
       [0.6]])

In [28]:
np.savetxt('climate_data', 
            climate_data,
            fmt='%.2f',
            header='temperature,rainfall,humidity,yeild_apples',
            comments=' ')

# Arithmetic operations and broadcasting

In [29]:
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 1, 2, 3]])

In [30]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [31]:
arr2 + arr3

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 12, 14, 16]])

In [32]:
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [33]:
arr2 + 3      # SOMAR 3 A TODOS OS ELEMENTOS DA LISTA NP

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [34]:
arr3 / 3    # DIVIDIR POR 3 A TODOS OS ELEMENTOS DA LISTA NP

array([[3.66666667, 4.        , 4.33333333, 4.66666667],
       [5.        , 5.33333333, 5.66666667, 6.        ],
       [6.33333333, 3.66666667, 4.        , 4.33333333]])

In [35]:
arr2.shape

(3, 4)

In [36]:
arr4 = np.array([4,5,6,7])

In [37]:
arr4.shape

(4,)

In [38]:
arr2 + arr4     # está somando [4,5,6,7] em todas as linhas       ex: [1,2,3,4] + [4,5,6,7]   //  [5, 6, 7, 8] + [4, 5, 6, 7]

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [39]:
arr5 = np.array([7, 8])

In [40]:
arr5.shape

(2,)

In [41]:
arr5_replicated = np.array([[7, 8],
                           [7, 8],
                           [7, 8]])

In [42]:
arr2 + arr5_replicated

ValueError: ignored

In [43]:
arr5 = np.array([[1, 2, 3], [3, 4, 5]])
arr6 = np.array([[2, 2, 3], [1, 2, 5]])

In [45]:
arr5 == arr6        # FAZ UMA COMPARAÇÃO DE ELEMENTO POR ELEMENTO

array([[False,  True,  True],
       [False, False,  True]])

In [46]:
arr5 != arr6        # FAZ UMA COMPARAÇÃO DE ELEMENTO POR ELEMENTO

array([[ True, False, False],
       [ True,  True, False]])

In [48]:
arr5 >= arr6       # FAZ UMA COMPARAÇÃO DE ELEMENTO POR ELEMENTO 

array([[False,  True,  True],
       [ True,  True,  True]])

In [49]:
arr5 <= arr6      # FAZ UMA COMPARAÇÃO DE ELEMENTO POR ELEMENTO

array([[ True,  True,  True],
       [False, False,  True]])

In [50]:
(arr5 == arr6).sum()      # SOMATÓRIA DE QNTS ELEMENTOS SÃO IGUAIS

3

In [51]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [57]:
climate_data[1]

array([39., 65., 70.])

In [56]:
climate_data_3d = np.array([ 
        [[10,20,30],
         [40,50,60]],

         [[70,80,90],
         [100,110,120]]])

In [61]:
climate_data_3d[1,1,1]

110

In [63]:
climate_data_3d[1][1][1]

110

In [70]:
climate_data_3d[1:, :2, 1:]     # MANIPULAÇÕES ESPECÍFICAS

array([[[ 80,  90],
        [110, 120]]])

In [71]:
climate_data_3d[1:, :2, 1:].shape

(1, 2, 2)

# CRIAR COM TUDO ZERO



In [73]:
np.zeros([3, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# CRIAR COM TODOS 1

In [76]:
np.ones([2,2,1])

array([[[1.],
        [1.]],

       [[1.],
        [1.]]])

# CRIAR RANDOM VETOR

In [77]:
np.random.rand(5)

array([0.56810051, 0.47120648, 0.23701204, 0.61635282, 0.05561383])

In [80]:
np.random.randn(2,3)    # GAUSSIAN

array([[ 0.93233373,  0.67342399,  0.63944253],
       [-0.48897963, -1.03652018,  0.32386653]])

In [81]:
np.full([2,3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [82]:
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [83]:
np.arange(10, 90, 3).shape

(27,)

In [84]:
np.arange(10, 90, 3).reshape(3, 3, 3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [94]:
np.linspace(3, 27, 4)     # SETA O ESPAÇAMENTO ENTRE O RANGE DE ACORDO COM O TANTO DE ELEMENTOS Q EU QUERO QUE TENHA NO RANGE (3, 27)

array([ 3., 11., 19., 27.])